force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/getStudentsAPI.cls
@RestResource(urlMapping='/getStudentsAPI') //https://https://orgfarm-81509904ff-dev-ed.develop.lightning.force.com/services/apexrest/getStudentsAPI
global with sharing class getStudentsAPI {

    @HttpGet
    global static List<Student__c> getStudents() {
        // You can add filters or limits as needed
      //  return [SELECT Id, Name FROM Student__c LIMIT 100];
        
        return [SELECT Id, Email__c, DOB__c, Phone__c, College__c FROM Student__c limit 5];
    }
}