force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CollegeSOAPService.cls
global class CollegeSOAPService { //SF custom SOAP WEBSERVICE

    webservice static List<College__c> getCollegesWithBudgetGreaterThan10000() {
        return [
            SELECT Id, Name, Total_Budget__c, Location__c,
                   (SELECT Id, Name  FROM Students__r)
            FROM College__c 
            WHERE Total_Budget__c > 10000
        ];
    }
    
     webservice static List<College__c> getColleges() {
        return [
            SELECT Id, Name, Total_Budget__c, Location__c FROM College__c 
            WHERE Total_Budget__c < 1000 limit 10
        ];
    }

        
    

    webservice static List<College__c> getCollegesWithBudgetGreaterThan50000() {
        return [
            SELECT Id, Name, Total_Budget__c, Location__c,
                   (SELECT Id, Name FROM Students__r)
            FROM College__c 
            WHERE Total_Budget__c > 50000
        ];
    }

    webservice static List<College__c> getCollegesWithBudgetGreaterThan90000() {
        return [
            SELECT Id, Name, Total_Budget__c, Location__c,
                   (SELECT Id, Name  FROM Students__r)
            FROM College__c 
            WHERE Total_Budget__c > 90000
        ];
    }
}